---

- hosts: base
  sudo: yes

  vars:
    - piku_version: "0.4.3"
    - ssh_keys: []
    - piku_username: "piku"
    - limits:
        soft: 16384
        hard: 32768
    - kernel:
        # increase maximum open files
        fs.file-max: 65535
        # maximize number of file watches
        fs.inotify.max_user_watches: 100000
        # swap only to avoid out of memory
        #vm.swappiness: 0
        vm.swappiness: 10
        # tweak filesystem page cache flushing
        vm.dirty_ratio: 80
        vm.dirty_background_ratio: 80
        vm.dirty_expire_centisecs: 12000
        # allowed local port range
        net.ipv4.ip_local_port_range: 2000 65535
        # number of times SYNACKs for passive TCP connections
        net.ipv4.tcp_synack_retries: 2
        # decrease the time default value for tcp_fin_timeout connection
        net.ipv4.tcp_fin_timeout: 15
        # decrease the time default value for connections to keep alive
        net.ipv4.tcp_keepalive_time: 300
        net.ipv4.tcp_keepalive_probes: 5
        net.ipv4.tcp_keepalive_intvl: 15
        # default Socket Receive Buffer
        net.core.rmem_default: 31457280
        # maximum Socket Receive Buffer
        net.core.rmem_max: 12582912
        # default Socket Send Buffer
        net.core.wmem_default: 31457280
        # maximum Socket Send Buffer
        net.core.wmem_max: 12582912
        # number of incoming connections
        net.core.somaxconn: 4096
        # number of incoming connections backlog
        net.core.netdev_max_backlog: 65536
        # maximum amount of option memory buffers
        net.core.optmem_max: 25165824
        # maximum total buffer-space
        # measured in pages (4096 bytes)
        net.ipv4.tcp_mem: 65536 131072 262144
        net.ipv4.udp_mem: 65536 131072 262144
        # read-buffer space
        net.ipv4.tcp_rmem: 8192 87380 16777216
        net.ipv4.udp_rmem_min: 16384
        # increase the write-buffer-space
        net.ipv4.tcp_wmem: 8192 65536 16777216
        net.ipv4.udp_wmem_min: 16384
        # increase the tcp-time-wait buckets pool size to prevent simple DOS attacks
        net.ipv4.tcp_max_tw_buckets: 1440000
        net.ipv4.tcp_tw_recycle: 1
        net.ipv4.tcp_tw_reuse: 1
        # protect Against TCP Time-Wait
        net.ipv4.tcp_rfc1337: 1
        # disable slow start
        net.ipv4.tcp_slow_start_after_idle: 0
        # allow reuse of TIME_WAIT sockets
        net.ipv4.tcp_tw_reuse: 1


  roles:
    - base

